version: '3.3'

services:
  amalanche:
    entrypoint: 'npm run dev'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_HOST}:${MONGO_PORT}/
